# Generated by Django 4.0.6 on 2023-08-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ignis_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('date', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ignis_app.user')),
            ],
        ),
    ]
