# Generated by Django 4.0.6 on 2023-08-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ignis_app', '0004_alter_events_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ignis_app.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ignis_app.user')),
            ],
        ),
    ]
