# Generated by Django 4.0.6 on 2023-08-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ignis_app', '0005_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ignis_app.events'),
        ),
    ]
